// lib/bonds/cash-flows.ts
import type { BondParams, CashFlow } from "./types";

/**
 * Generate all cash flows for a bond from first coupon after purchase to maturity.
 * Coupon dates are generated by stepping backward from maturity date by coupon period.
 */
export function generateCashFlows(bond: BondParams): CashFlow[] {
  const { faceValue, couponRate, couponFrequency, maturityDate, purchaseDate } = bond;
  const couponAmount = faceValue * couponRate / couponFrequency;
  const monthsPerPeriod = 12 / couponFrequency;

  // Generate coupon dates by stepping backward from maturity
  const maturity = new Date(maturityDate + "T00:00:00");
  const purchase = new Date(purchaseDate + "T00:00:00");
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const couponDates: Date[] = [];
  let d = new Date(maturity);
  while (d > purchase) {
    couponDates.unshift(new Date(d));
    d = new Date(d);
    d.setMonth(d.getMonth() - monthsPerPeriod);
  }

  // Build cash flows
  let cumulative = 0;
  const flows: CashFlow[] = couponDates.map((date, i) => {
    const isLast = i === couponDates.length - 1;
    const amount = isLast ? couponAmount + faceValue : couponAmount;
    cumulative += amount;
    const dateStr = date.toISOString().split("T")[0];

    return {
      date: dateStr,
      type: isLast ? "coupon+principal" : "coupon",
      amount,
      cumulativeAmount: cumulative,
      status: date <= today ? "collected" : "pending",
    };
  });

  return flows;
}
