// Trigger fill-prices for Felipe Fortt bypassing auth
// Run: node scripts/backfill-fortt.mjs

import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';

// We can't bypass auth on the API route easily, so we'll call it via
// the deployed URL with a service-role workaround.
// Actually, the easiest is: just open the seguimiento page for this client
// and click "Actualizar Precios".

// But let's check if there's a cron/internal endpoint...
// The cron uses vercel cron which calls specific endpoints.

// Alternative: delete stale api-prices and let the next fill-prices run regenerate them.
// Let's just delete api-prices between the two cartolas so fill-prices regenerates everything.

import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const CLIENT_ID = '0f0e0931-977f-4e1f-b506-d3a120e06124';

// Delete all existing api-prices snapshots (they'll be regenerated by fill-prices)
const { data: existing, error: countErr } = await sb.from('portfolio_snapshots')
  .select('id', { count: 'exact' })
  .eq('client_id', CLIENT_ID)
  .eq('source', 'api-prices');

console.log(`Found ${existing?.length || 0} api-prices snapshots to delete`);

if (existing && existing.length > 0) {
  const { error } = await sb.from('portfolio_snapshots')
    .delete()
    .eq('client_id', CLIENT_ID)
    .eq('source', 'api-prices');

  if (error) {
    console.error('Delete error:', error);
    process.exit(1);
  }
  console.log('Deleted all api-prices snapshots. Now run fill-prices from the UI.');
} else {
  console.log('No api-prices to delete.');
}

console.log('\nNext step: Go to Seguimiento > Felipe Fortt > click "Actualizar Precios"');
console.log('fill-prices will regenerate daily snapshots from Sep 2025 to today.');
